version: "3.9"
services:
  web:
    platform: linux/x86_64
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --host 0.0.0.0
    volumes:
      - ".:/app"
      - bundle:/bundle
    ports:
      - "4000:4000"
volumes:
  bundle: